application: crowd-navigation
version: 1-3c
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /js
  static_dir: js
  
- url: /media
  static_dir: media
  
- url: /font
  static_dir: font 
  
# Endpoints handler
- url: /_ah/spi/.*
  script: crowdnavigation_api.APPLICATION

inbound_services:
- channel_presence

libraries:
- name: jinja2
  version: latest

- name: markupsafe
  version: latest
  
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0