application: crowd-navigation
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /images
  static_dir: static/images

- url: /js
  static_dir: js
  
- url: /.*
  script: crowdnavigation.py

inbound_services:
- channel_presence

libraries:                                                                      
- name: jinja2                                                                  
  version: latest                                                               

- name: markupsafe                                                              
  version: latest